package org.natwest.model;

import javax.xml.bind.annotation.XmlRootElement;
import java.util.List;

/*
Class to build the prime number response result.
initial: is the requested parameter, for which application has generated the prime number
primes: all the prime number generated by the application given an initial
 */
@XmlRootElement
public class PrimeNumberResult {

    private final int initial;
    private final List<Integer> primes;

    public PrimeNumberResult(int initial, List<Integer> primes) {
        this.initial = initial;
        this.primes = primes;
    }

    public int getInitial() {
        return initial;
    }

    public List<Integer> getPrimes() {
        return primes;
    }
}
